routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\OrderController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Route::resource('customer', CustomerController::class)->middleware(['auth']);

Route::resource('order', OrderController::class)->middleware(['auth']);

Route::get('dashboard', function (){
    return (new CustomerController())->index();
})->middleware(['auth'])->name('dashboard');

Route::get('/dashboard2', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard2');

require __DIR__.'/auth.php';

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    protected $primaryKey = 'id_order';

    protected $fillable = ['id_cust','order_date', 'total_price', 'paid'];
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;

use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Order::all();
        return view('order.index', compact('data'));

        //PAGINATION
        // $data = Customer::latest()->paginate(5);

        // return view('customer.index', compact('data'))
        //     ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('order.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Validate requests
        $request->validate([
            'order_date' => 'required',
            'total_price' => 'required',
            'paid' => 'required',
        ]);

        Order::create(
            $request->all()
        );

        return redirect()->route('dashboard')
                        ->with('success','Order successfully added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function show(Order $order)
    {
        $data = Order::find($order->id_order)->orders;

        return view('order.show', compact('data', 'order'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function edit(Order $order)
    {
        return view('order.edit', compact('order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Order $order)
    {
        // Validate requests
        $request->validate([
            'order_date' => 'required',
            'total_price' => 'required',
            'paid' => 'required',
        ]);

        $order->update(
            $request->all()
        );

        return redirect()->route('dashboard')
                        ->with('success','Order successfully updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Customer  $customer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Order $order)
    {
        //
        $order->delete();

        return redirect()->route('dashboard')
                        ->with('success','Order deleted successfully');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/order/create.blade.php
@extends('layouts.layout-order')

@section('title', 'Add Order')

@section('add-css')
    <style>
        .form-input,
        .form-textarea,
        .form-select,
        .form-multiselect {
            background-color: #edf2f7;
        }
    </style>
@endsection

@section('content')
    <div class="mt-10 text-4xl font-bold" style="color: #474747">
        Add Order
    </div>

    <!--Card-->
    <div class="w-3/4 p-8 mt-10 bg-white rounded shadow">
        <form action="{{ route('order.store') }}" method="POST">
            @csrf

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="id_cust">
                        ID Customer
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="id_cust" name="id_cust" type="bigInteger" value="">
            </div>
            </div>

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="order_date">
                        Order Date
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="order_date" name="order_date" type="date" value="">
            </div>
            </div>

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="total_price">
                        Total Price
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="total_price" name="total_price" type="bigInteger" value="">
            </div>
            </div>

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="paid">
                        Paid
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="paid" name="paid" type="bigInteger" value="">
            </div>
        </div>

            <div class="md:flex md:items-center">
                <div class="md:w-1/3"></div>
                <div class="md:w-2/3">
                    <input type="submit" class="px-4 py-2 font-bold text-white bg-purple-700 rounded shadow hover:bg-purple-500 focus:shadow-outline focus:outline-none">
                </div>
            </div>
        </form>

@endsection

resources/views/order/edit.blade.php
@extends('layouts.layout-order')

@section('title', 'Edit Order')

@section('add-css')
    <style>
        .form-input,
        .form-textarea,
        .form-select,
        .form-multiselect {
            background-color: #edf2f7;
        }
    </style>
@endsection

@section('content')
    <div class="mt-10 text-4xl font-bold" style="color: #474747">
        Edit Order
    </div>

    <!--Card-->
    <div class="w-3/4 p-8 mt-10 bg-white rounded shadow">
        <form action="{{ route('order.update', $order->id_order) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="id_cust">
                        ID Customer
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="id_cust" name="id_cust" type="bigInteger" value="">
            </div>
            </div>

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="order_date">
                        Order Date
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="order_date" name="order_date" type="date" value="">
            </div>
            </div>

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="total_price">
                        Total Price
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="total_price" name="total_price" type="bigInteger" value="">
            </div>
            </div>

            <div class="mb-6 md:flex">
                <div class="md:w-1/3">
                    <label class="block pr-4 mb-3 font-bold text-gray-600 md:text-left md:mb-0" for="paid">
                        Paid
                    </label>
                </div>
                <div class="md:w-2/3">
                    <input class="block w-full form-input focus:bg-white" id="paid" name="paid" type="bigInteger" value="">
            </div>
        </div>

            <div class="md:flex md:items-center">
                <div class="md:w-1/3"></div>
                <div class="md:w-2/3">
                    <input type="submit" class="px-4 py-2 font-bold text-white bg-purple-700 rounded shadow hover:bg-purple-500 focus:shadow-outline focus:outline-none">
                </div>
            </div>
        </form>

@endsection

resources/views/order/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Order Dashboard') }}
        </h2>
    </x-slot>

    <div class="max-w-6xl mx-auto">
    <div class="flex flex-col items-center justify-center mx-5 md:mx-0">

    @if ($message = Session::get('success'))
        <div>
            <p>{{ $message }}</p>
        </div>
    @endif

        <a href="{{ route('order.create') }}" class="px-3 py-1 mt-3 text-sm font-bold text-purple-700 border-2 border-purple-600 rounded-lg">
            + | Data Order
    </a>

    <table class="w-full mt-10 table-fixed">
        <thead>
        <tr class="text-white bg-purple-500 shadow-lg">
            <th class="py-2">ID Customer</th>
            <th class="py-2">Order date</th>
            <th class="py-2">Total price</th>
            <th class="py-2">Paid</th>
        </tr>
        </thead>
        <tbody>
        @foreach ($data as $key => $value)
        <tr>
            <td class="py-4 text-center border-b-2 border-gray-300">{{ $value->order_date }}</td>
            <td class="text-center border-b-2 border-gray-300">{{ $value->total_price }}</td>
            <td class="text-center capitalize border-b-2 border-gray-300">{{ $value->paid }}</td>
            <td class="text-center border-b-2 border-gray-300">
                <form action="{{ route('order.destroy', $value->id_order) }}" method="POST">
                    <div class="flex justify-center space-x-4 font-bold">
                        <a href="{{ route('order.show', $value->id_order) }}" class="text-blue-500">Detail Order</a>

                        @csrf
                        @method('DELETE')
                        <button class="text-red-500">Delete</a>
                    </div>
                </form>
            </td>
        </tr>
        @endforeach
        </tbody>
    </table>


    </div>
    </div>
</x-app-layout>

resources/views/order/show.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-gray-800">
            {{ __('Order Detail') }}
        </h2>
    </x-slot>

    <div class="max-w-6xl mx-auto">
    <div class="flex flex-col items-center justify-center mx-5 md:mx-0">
        @if ($message = Session::get('success'))
            <div>
                <p>{{ $message }}</p>
            </div>
        @endif

        <div class="mt-10 text-4xl font-bold" style="color: #474747">
                Detail Order
        </div>
        <a href="{{ route('order.edit', $order->id_order) }}" class="px-3 py-1 mt-3 text-sm font-bold text-purple-700 border-2 border-purple-600 rounded-lg">
                Edit Data Order
        </a>

        <div class="flex flex-col text-center">
            @foreach ($data as $item)
            <div>{{ $item->id_cust }}</div>
            <div>{{ $item->order_date }}</div>
            <div>{{ $item->total_price }}</div>
            <div>{{ $item->paid }}</div>
            @endforeach
        </div>
    </div>
    </div>

</x-app-layout>